name: Model request
labels: ['model request']
description: Request a new model.
body:
  - type: textarea
    id: problem
    attributes:
      label: What model would you like?
      description: Please provide a link to the model.
